window.scheduleData = {
    disciplineMapping: {
        'NEF': 'Nefrologia', 'CIR': 'Cirurgia', 'GIN': 'Ginecologia', 'PRE': 'Preventiva', 'OBS': 'Obstetrícia',
        'PED': 'Pediatria', 'REU': 'Reumatologia', 'HEM': 'Hematologia', 'GAS': 'Gastroenterologia',
        'HEP': 'Hepatologia', 'CAR': 'Cardiologia', 'END': 'Endocrinologia', 'PNE': 'Pneumologia',
        'INF': 'Infectologia', 'NEU': 'Neurologia', 'PSQ': 'Psiquiatria', 'ORT': 'Ortopedia',
        'DER': 'Dermatologia', 'OFT': 'Oftalmologia'
    },
    
    get disciplines() {
        return [...new Set(Object.values(this.disciplineMapping))].sort();
    },

    apostilasData: {
        "NEF 01": { bonusLessons: ["Lesão Renal na Hipertensão e Doenças Hematológicas", "Rim e o Diabetes", "Rim e as Colagenoses", "Rim e as Vasculites", "Rim e Doenças Infecciosas Sistêmicas", "Rim e Situações Diversas"] },
        "CIR 01": { bonusLessons: ["Trauma - Preparação e Triagem", "Trauma Cervical e Fraturas de Face", "Trauma Diafragmático", "Embolia Gordurosa", "Trauma Vascular Abdominal", "Trauma Abdominal - Lesões Específicas", "Trauma de Uretra e Bexiga", "Trauma Cranioencefálico", "Lesão Renal", "Morte Encefálica", "Trauma da Coluna Vertebral e Raquimedular"] },
        "NEF 02": { bonusLessons: ["Nefrotoxicidade por Antimicrobianos", "Nefrotoxicidade por Analgésicos", "Nefrotoxicidade por Metais pesados", "Nefrotoxicidade por Contraste", "Acidose Tubular Renal", "Rabdomiólise"] },
        "GIN 01": { bonusLessons: ["Síndrome pré-menstrual e Transtorno disfórico pré-menstrual"] },
        "PRE 01": { bonusLessons: ["Outros indicadores e Atualizações Censo 2022", "Sistemas de Informação"] },
        "NEF 03": { bonusLessons: ["Relação Delta-Delta", "Aspectos práticos no tratamento da Hiponatremia", "Terapia de Substituição renal – HD e DP", "Terapia de Substituição renal - Transplante"] },
        "OBS 01": { bonusLessons: ["Aconselhamento genético pré-natal"] },
        "PRE 02": { bonusLessons: ["Estudos descritivos e Metanálise", "Fases do ensaio clínico", "Testes estatísticos", "Variáveis", "Curva ROC e Variações do ponto de corte", "Medidas de tendência central e dispersão", "Verossimilhança e Testes múltiplos"] },
        "PED 01": { bonusLessons: ["Exame físico Neonatal", "Doenças do Trato Gastrointestinal", "Triagem Neonatal", "Miscelânea"] },
        "CIR 02": { bonusLessons: ["Câncer de Bexiga", "Câncer de Rim", "Suporte nutricional", "Cirurgia Plástica", "Úlceras de Pressão", "Cicatrização de feridas", "Choque - Monitorização", "Choque - Tratamento"] },
        "REU 01": { bonusLessons: ["Anti-inflamatórios e Glicocorticoides", "Febre familiar do mediterrâneo", "Fibromialgia"] },
        "PRE 03": { bonusLessons: ["Ética médica - Artigos principais, erros e atualizações", "Glossário de Doenças infecciosas", "Saúde do trabalhador - Agrotóxicos", "Saúde do trabalhador - CAT e Tipos de acidentes", "Saúde do trabalhador - Pneumoconioses, Pair e Burnout", "Saúde do trabalhador - Saturnismo, hidrargirismo, benzenismo e cromo", "Raiva"] },
        "REU 02": { bonusLessons: ["Artrite séptica", "Amiloidose", "Policondrite recidivante"] },
        "HEM 01": { bonusLessons: ["Anemia aplasica", "Anemia sideroblastica", "Mielodisplasias", "Alfa-talassemia", "Hemoglobinúria paroxística noturna"] },
        "CIR 03": { bonusLessons: ["Hérnias - Abordagem videolaparoscópica", "Hérnias na infância", "Outras hérnias", "Anestesiologia", "Profilaxia do TEP e TVP", "Tipos de tela", "Fios de sutura", "Fístula digestiva e deiscência", "Projeto ERAS e ACERTO"] },
        "HEM 02": { bonusLessons: ["Doenças mioproliferativas", "Hemofilias", "Esplenomegalia", "Tromboelastrograma", "Hemotransfusão"] },
        "GAS 01": { bonusLessons: ["Anatomia do esôfago", "Esofagites", "Ingestão de corpo estranho", "Hérnia de hiato", "Perfuração de esôfago", "Divertículos esofágicos", "Anatomia do estômago", "Síndrome de Zollinger-Ellison", "GIST", "Linfoma gástrico"] },
        "GIN 02": { bonusLessons: ["Pólipos endometriais e Dismenorreia"] },
        "GAS 02": { bonusLessons: ["Anatomia do cólon", "Colite pseudomembranosa", "Síndrome do intestino irritável", "Tumores carcinoides"] },
        "GAS 03": { bonusLessons: ["Anatomia do pâncreas", "Cirurgias pancreáticas", "Neoplasias císticas do pâncreas", "Tumores neuroendocrinos do pâncreas", "Anatomia das vias biliares", "Abscesso hepático", "Cistos de via biliar", "Lesão iatrogênica das vias biliares", "Neoplasias das vias biliares", "Tumores hepáticos benignos", "Tumores hepáticos malignos"] },
        "HEP 01": { bonusLessons: ["Insuficiência hepática aguda"] },
        "HEP 02": { bonusLessons: ["Anatomia do fígado", "Hepatite medicamentosa", "Cirurgia de hipertensão portal", "Transplante hepático"] },
        "GIN 03": { bonusLessons: ["Osteoporose", "Fístulas genitais e Síndrome da bexiga dolorosa"] },
        "CAR 01": { bonusLessons: ["Anatomia cardíaca", "Bloqueio de Ramo", "Marca-passo - Conceitos básicos", "Marca-passo - Funcionamento"] },
        "CAR 02": { bonusLessons: ["Cardiomiopatia hipertrófica", "Cardiomiopatia de estresse", "Cardiomiopatia dilatada", "Cardiomiopatia restritiva", "Pericardiopatias", "Hipertensão pulmonar"] },
        "CAR 03": { bonusLessons: ["Complicações Pós-IAM"] },
        "GIN 04": { bonusLessons: [] },
        "GIN 05": { bonusLessons: ["Neoplasia intraepitelial vulvar", "Câncer de vulva", "Distúrbios do humor e Tromboembolismo"] },
        "PRE 04": { bonusLessons: ["Genograma e Ecomapa", "Decreto 7508", "Método Clínico Centrado na Pessoa", "Método SOAP", "Politica Nacional de Humanização", "Redes e Programas Principais do SUS", "Instrumentos de AB (Ciclo de Vida Familiar)", "Instrumentos de AB (Tipos de Família)", "Instrumentos de AB (Escala de Coelho Savassi)", "Instrumentos de AB (Apgar Familiar, Practice e Firo)", "Saúde Suplementar", "Princípios da MFC", "Saúde e o Mundo", "Pacto pela Saúde 2006", "Portaria N635, 22 de maio de 2023", "Receitas Medicas"] },
        "END 01": { bonusLessons: ["Anatomia da Tireoide", "Eutireoideo doente", "Hipotireoidismo congênito"] },
        "END 02": { bonusLessons: ["Hipófise e Hipotálamo", "Hiperparatireoidismo primário", "Hiperparatireoidismo secundário e terciário", "Incidentaloma adrenal", "Hiperplasia adrenal congênito", "Neoplasia endócrina múltipla", "Hipoparatireoidismo", "Anatomia da Hipófise e Hipotálamo", "Anatomia da Adrenal", "Raquitismo e Osteomalácia"] },
        "END 03": { bonusLessons: ["Dislipidemia", "Obesidade - Introdução", "Obesidade - Fisiopatologia e Tratamento clínico", "Obesidade - Cirurgia bariátrica", "Obesidade - Alterações funcionais pós-bariátrica", "Hipoglicemia", "Pé diabético"] },
        "PED 02": { bonusLessons: [] },
        "PED 03": { bonusLessons: [] },
        "PED 04": { bonusLessons: ["Constipação na Infância", "Diarreia crônica", "Rinite Alérgica", "Estridor crônico e Aspiração de corpo estranho", "Fibrose cística"] },
        "PNE 01": { bonusLessons: ["Ventilação mecânica", "Sarcoidose", "Pneumopatias intersticiais difusas", "Nódulo pulmonar difuso", "Síndrome do desconforto respiratório agudo"] },
        "OBS 02": { bonusLessons: [] },
        "OBS 03": { bonusLessons: [] },
        "OBS 04": { bonusLessons: [] },
        "OBS 05": { bonusLessons: [] },
        "PNE 02": { bonusLessons: ["Derrame pleural"] },
        "INF 01": { bonusLessons: ["HIV na Infância", "HTLV", "Profilaxia da transmissão vertical do HIV", "Abscesso pulmonar", "Derrame pleural parapneumônico", "Sepse e choque séptico"] },
        "INF 02": { bonusLessons: ["Abscesso hepático", "Piodermites", "Acidente por animais peçonhentos", "Infecção relacionada ao cateter", "Osteomielite"] },
        "INF 03": { bonusLessons: ["Febre Maculosa Brasileira", "Infecção do trato urinário", "COVID-19", "Monkeypox", "Leishmaniose visceral", "Malária"] },
        "GIN 06": { bonusLessons: ["HIV e Gestação"] },
        "PED 05": { bonusLessons: ["PALS", "Cardiopatias congênitas", "Anafilaxia", "Hipertensão arterial", "Prevenção de Acidentes e Maus-tratos na Infância", "Erros inatos da Imunidade", "Tumores Abdominais na Infância", "Febre sem sinais localizatórios"] },
        "NEU 01": { bonusLessons: ["Hipertensão intracraniana", "Doenças da placa motora", "Intoxicações exógenas"] },
        "CIR 04": { bonusLessons: ["Anatomia do Reto e Canal anal", "CIPE - Afecções cervical", "CIPE - Gastrointestinal 1", "CIPE - Gastrointestinal 2", "CIPE - Gastrointestinal 3", "CIPE - Geniturinário e Tumores", "Cirurgia de cabeça e pescoço", "Colangite esclerosante primária"] },
        "PSQ 01": { bonusLessons: ["Suicídio", "Transtornos do neurodesenvolvimento"] },
        "ORT 01": { bonusLessons: ["Doenças periarticulares"] },
        "DER 01": { bonusLessons: ["Monkeypox", "Acne"] },
        "OFT 01": { bonusLessons: [] }
    },

    weeklyLayout: [
      { week: 1, modules: [ { code: "NEF 01", title: "Glomerulopatias I (Nefrítica, Alterações assintomáticas, GNRP)", lessons: [] }, { code: "CIR 01", title: "Trauma I – Primeiro atendimento, cabeça e tórax", lessons: [] } ] },
      { week: 2, modules: [ { code: "NEF 01", title: "Glomerulopatias II (Nefrótica, Glomerulopatias nas desordens)", lessons: [] }, { code: "CIR 01", title: "Trauma II – Abdome e TCE", lessons: [] } ] },
      { week: 3, modules: [ { code: "NEF 02", title: "Doenças Tubulosintersticiais e Vasculares Renais", lessons: [] }, { code: "GIN 01", title: "Ciclo Menstrual e Anticoncepção", lessons: [] } ] },
      { week: 4, modules: [ { code: "NEF 03", title: "Distúrbios Hidroeletrolíticos", lessons: [] }, { code: "GIN 01", title: "Amenorreia e Ovário Policístico", lessons: [] } ] },
      { week: 5, modules: [ { code: "PRE 01", title: "Medidas de Saúde Coletiva", lessons: [] }, { code: "NEF 03", title: "Distúrbios Ácido-Básico", lessons: [] } ] },
      { week: 6, modules: [ { code: "NEF 03", title: "Insuficiência Renal", lessons: [] }, { code: "OBS 01", title: "Diagnóstico de Gravidez, Modificações do Organismo e Pré-natal", lessons: [] } ] },
      { week: 7, modules: [ { code: "PRE 02", title: "Estudos Epidemiológicos", lessons: [] }, { code: "PED 01", title: "Neonatologia I", lessons: [] } ] },
      { week: 8, modules: [ { code: "PRE 02", title: "Epidemiologia Clínica", lessons: [] }, { code: "PED 01", title: "Neonatologia II", lessons: [] } ] },
      { week: 9, modules: [ { code: "REU 01", title: "Introdução à Reumatologia e Artrites (Reumatóide, Espondiloartropatias soronegativas)", lessons: [] }, { code: "CIR 02", title: "Nefrolitíase, Câncer de Próstata e HPB", lessons: [] } ] },
      { week: 10, modules: [ { code: "REU 01", title: "Gota e Febre Reumática", lessons: [] }, { code: "CIR 02", title: "REMIT e Queimaduras", lessons: [] } ] },
      { week: 11, modules: [ { code: "REU 02", title: "Colagenoses – Parte I (Polimiosite, Dermatomiosite, DMTC, Esclerodermia)", lessons: [] }, { code: "OBS 02", title: "Assistência clínica ao Parto e Parto Prematuro", lessons: [] } ] },
      { week: 12, modules: [ { code: "REU 02", title: "Colagenoses – Parte II (LES e Sjogren)", lessons: [] }, { code: "PRE 03", title: "Vigilância da Saúde e Processo Epidêmico", lessons: [] } ] },
      { week: 13, modules: [ { code: "REU 02", title: "Vasculites", lessons: [] }, { code: "PED 02", title: "Aleitamento Materno", lessons: [] } ] },
      { week: 14, modules: [ { code: "HEM 01", title: "Anemias I – Ferropriva, Doenças Crônicas e Megaloblástica", lessons: [] }, { code: "CIR 03", title: "Hérnias da Parede Abdominal", lessons: [] } ] },
      { week: 15, modules: [ { code: "HEM 01", title: "Anemias II – Hemolíticas, Falciformes e Hemoglobinopatias", lessons: [] }, { code: "CIR 03", title: "Preparo Pré-operatório, Risco cirúrgico e Complicações em Cirurgia", lessons: [] } ] },
      { week: 16, modules: [ { code: "HEM 02", title: "Leucemias Agudas e Crônicas", lessons: [] }, { code: "HEM 02", title: "Linfomas e Mieloma Múltiplo", lessons: [] } ] },
      { week: 17, modules: [ { code: "HEM 02", title: "Distúrbios da Hemostasia", lessons: [] }, { code: "PED 02", title: "Crescimento, Desenvolvimento e Puberdade", lessons: [] } ] },
      { week: 18, modules: [ { code: "GAS 01", title: "Doenças do Esôfago", lessons: [] }, { code: "GIN 02", title: "Sangramento Uterino Anormal, Endometriose e Infertilidade", lessons: [] } ] },
      { week: 19, modules: [ { code: "GAS 01", title: "Doenças do Estômago e EXTRA: Hemorragia Digestiva Alta", lessons: [] }, { code: "GAS 02", title: "Síndrome de Má-absorção e Doença Intestinal Inflamatória", lessons: [] } ] },
      { week: 20, modules: [ { code: "GAS 02", title: "Doença Vascular dos Intestinos e Obstrução Intestinal", lessons: [] }, { code: "OBS 03", title: "Sangramentos na Gravidez – Parte 1", lessons: [] } ] },
      { week: 21, modules: [ { code: "GAS 02", title: "Diverticulose, Polipose, Câncer de Cólon e Apendicite Aguda; EXTRA: Hemorragia Digestiva Baixa", lessons: [] }, { code: "OBS 03", title: "Sangramentos na Gravidez – Parte 2 e Doença Hemolítica Perinatal", lessons: [] } ] },
      { week: 22, modules: [ { code: "GAS 03", title: "Pancreatite Aguda e Crônica e Câncer de Pâncreas", lessons: [] }, { code: "GAS 03", title: "Doenças das Vias Biliares", lessons: [] } ] },
      { week: 23, modules: [ { code: "HEP 01", title: "Introdução à Hepatologia e Hepatites Virais", lessons: [] }, { code: "HEP 02", title: "Cirrose e suas Causas", lessons: [] } ] },
      { week: 24, modules: [ { code: "HEP 02", title: "Cirrose e suas Complicações, Hipertensão Porta (Tratamento clínico e cirúrgico), Ascite e Encefalopatia", lessons: [] }, { code: "GIN 03", title: "Climatério, Distopias e Incontinência urinária", lessons: [] } ] },
      { week: 25, modules: [ { code: "CAR 01", title: "Arritmias I (Taquiarritmias)", lessons: [] }, { code: "PED 03", title: "Distúrbios do Crescimento, Desnutrição e Baixa estatura", lessons: [] } ] },
      { week: 26, modules: [ { code: "CAR 01", title: "Arritmias II (Bradiarritmias) e PCR", lessons: [] }, { code: "PED 03", title: "Imunização", lessons: [] } ] },
      { week: 27, modules: [ { code: "CAR 02", title: "Insuficiência Cardíaca", lessons: [] }, { code: "GIN 04", title: "Doenças das Mamas e Ovários", lessons: [] } ] },
      { week: 28, modules: [ { code: "CAR 02", title: "Hipertensão Arterial Sistêmica, Crise Hipertensiva", lessons: [] }, { code: "CAR 02", title: "Valvopatias", lessons: [] } ] },
      { week: 29, modules: [ { code: "CAR 03", title: "Doença Arterial Coronariana: IAM e Angina", lessons: [] }, { code: "PED 04", title: "Diarreia Aguda e Desidratação na Infância", lessons: [] } ] },
      { week: 30, modules: [ { code: "END 01", title: "Tireoide I (Hipertireoidismo)", lessons: [] }, { code: "GIN 05", title: "Lesões Precursoras, Câncer de Colo Uterino e Endométrio", lessons: [] } ] },
      { week: 31, modules: [ { code: "PRE 04", title: "SUS – Evolução histórica, Diretrizes, Propostas e Financiamento", lessons: [] }, { code: "END 01", title: "Tireoide II (Tireoidites e Câncer)", lessons: [] } ] },
      { week: 32, modules: [ { code: "END 02", title: "Doenças da Suprarrenal", lessons: [] }, { code: "PED 04", title: "Infecções Respiratórias Agudas – Parte 1", lessons: [] } ] },
      { week: 33, modules: [ { code: "END 03", title: "Diabetes Mellitus, Dislipidemia e Obesidade", lessons: [] }, { code: "PED 04", title: "Infecções Respiratórias Agudas – Parte 2", lessons: [] } ] },
      { week: 34, modules: [ { code: "PNE 01", title: "Asma e DPOC", lessons: [] }, { code: "OBS 04", title: "Distúrbios Hipertensivos da Gestação, Diabetes e Gemelaridade", lessons: [] } ] },
      { week: 35, modules: [ { code: "PNE 01", title: "Câncer de Pulmão e TEP", lessons: [] }, { code: "PED 05", title: "Nefrologia Pediátrica", lessons: [] } ] },
      { week: 36, modules: [ { code: "PNE 02", title: "Tuberculose", lessons: [] }, { code: "PNE 02", title: "Pneumonia e Complicações", lessons: [] } ] },
      { week: 37, modules: [ { code: "INF 01", title: "AIDS", lessons: [] }, { code: "OBS 05", title: "Sofrimento Fetal, Vitalidade Fetal, Fórcipes e Puerpério", lessons: [] } ] },
      { week: 38, modules: [ { code: "INF 02", title: "Endocardite Infecciosa e Meningite", lessons: [] }, { code: "INF 02", title: "Parasitoses Intestinais", lessons: [] } ] },
      { week: 39, modules: [ { code: "INF 03", title: "Síndromes Febris", lessons: [] }, { code: "GIN 06", title: "Vulvovaginites, IST e Cervicites", lessons: [] } ] },
      { week: 40, modules: [ { code: "NEU 01", title: "Neurologia I (Síndromes Neurológicas e AVE)", lessons: [] }, { code: "PED 05", title: "Doenças Exantemáticas na Infância", lessons: [] } ] },
      { week: 41, modules: [ { code: "NEU 01", title: "Neurologia II ((Polineuropatias, Demência e Parkinson))", lessons: [] }, { code: "NEU 01", title: "Neurologia III (Cefaleia e Epilepsia)", lessons: [] } ] },
      { week: 42, modules: [ { code: "CIR 04", title: "Especialidades Cirúrgicas – Parte 1", lessons: [] }, { code: "CIR 04", title: "Especialidades Cirúrgicas – Parte 2", lessons: [] } ] },
      { week: 43, modules: [ { code: "PSQ 01", title: "Psiquiatria – Parte 1", lessons: [] }, { code: "PSQ 01", title: "Psiquiatria – Parte 2", lessons: [] } ] },
      { week: 44, modules: [ { code: "ORT 01", title: "Ortopedia – Parte 1", lessons: [] }, { code: "ORT 01", title: "Ortopedia – Parte 2", lessons: [] } ] },
      { week: 45, modules: [ { code: "DER 01", title: "Dermatologia – Parte 1", lessons: [] }, { code: "DER 01", title: "Dermatologia – Parte 2", lessons: [] } ] },
      { week: 46, modules: [ { code: "OFT 01", title: "Oftalmologia – Parte 1", lessons: [] }, { code: "OFT 01", title: "Oftalmologia – Parte 2", lessons: [] } ] }
    ]
};

